apiVersion: v1
kind: Service
metadata:
  name: {{ include "smalland.fullname" . }}
  labels:
    {{- include "smalland.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer"}}
  externalIPs:
  {{- range $externalIP := .Values.service.externalIPs }}
    - {{ $externalIP }}
  {{- end }}
  {{- end }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "smalland.selectorLabels" . | nindent 4 }}
