apiVersion: v1
kind: Service
metadata:
  name: {{ include "yuzu-multiplayer-server.fullname" . }}
  labels:
    {{- include "yuzu-multiplayer-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer"}}
  externalIPs:
  {{- range $externalIP := .Values.service.externalIPs }}
    - {{ $externalIP }}
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: game
      protocol: UDP
      name: game
  selector:
    {{- include "yuzu-multiplayer-server.selectorLabels" . | nindent 4 }}
