apiVersion: v2
appVersion: 4.10.0
description: |
  Dependency-Track is an intelligent Software Supply Chain Component Analysis platform that allows organizations to identify and reduce risk from the use of third-party and open source components. Dependency-Track takes a unique and highly beneficial approach by leveraging the capabilities of Software Bill-of-Materials (SBOM). This approach provides capabilities that traditional Software Composition Analysis (SCA) solutions cannot achieve.
name: dependency-track
home: https://dependencytrack.org/
version: 0.0.7
icon: https://raw.githubusercontent.com/DependencyTrack/dependency-track/master/docs/images/dt-logo.svg
keywords:
  - security
  - dependency
  - dependency-track
  - OWASP
  - Supply Chain Component Analysis
maintainers:
  - name: 98jan
sources:
  - https://docs.dependencytrack.org/
  - https://github.com/98jan/helm-charts
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 13.x.x