apiVersion: v1
kind: Service
metadata:
  name: {{ include "dependency-track.apiserver.fullname" . }}-apiserver
  labels:
    {{- include "dependency-track.apiserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiserver.service.type }}
  ports:
    - port: {{ .Values.apiserver.service.port }}80
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "dependency-track.apiserver.selectorLabels" . | nindent 4 }}
